=== saitamsaitam/Web-sovelluskehitys_2/Teht_3 XML-dokumentti ja DTD/peopleDTD.dtd
<!ELEMENT people (husband)*>
<!ATTLIST husband employed CDATA "Yes">	<!-- CDATA = Character data. Default value = Yes -->
<!ELEMENT husband (name,secondName?,age,wife)>	<!-- Only one -->
<!ELEMENT name (#PCDATA)*>		<!-- Parserable Character Data -->
<!ELEMENT secondName (#PCDATA)>
<!ELEMENT age (#PCDATA)*>
<!ELEMENT wife (wname,secondName?,age)*>	<!-- Can be many of those. No need to address age again because its already done -->
<!ELEMENT wname (#PCDATA)*>

=== saitamsaitam/Web-sovelluskehitys_2/Teht_3 XML-dokumentti ja DTD/people.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE people SYSTEM "./peopleDTD.dtd">

<people>
	
	<husband employed="Yes">
		<name>John</name>
		<secondName>Gary</secondName>
		<age>40</age>
		<wife>
			<wname>Anna</wname>
			<age>30</age>
		</wife>
	</husband>

	<husband employed="No">
		<name>Jack</name>
		<age>25</age>
		<wife>
			<wname>Jane</wname>
			<secondName>Emma</secondName>
			<age>29</age>
		</wife>
	</husband>

</people>
