=== saitamsaitam/Web-sovelluskehitys_2/Teht_4 XML dokumentti ja skeema/Person/employeeSchema.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xsd:element name="person" />
	<xsd:element name="employee" type="fullpersoninfo" />

	<xsd:complexType name="personinfo">
		<xsd:sequence>
			<xsd:element name="firstname" type="xsd:string" />
			<xsd:element name="lastname" type="xsd:string" />
			<xsd:element name="age" type="xsd:integer" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="fullpersoninfo">
		<xsd:complexContent>
			<xsd:extension base="personinfo">
				<xsd:sequence>
					<xsd:element name="address" type="xsd:string" />
					<xsd:element name="city" type="xsd:string" />
					<xsd:element name="country" type="xsd:string" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

</xsd:schema>

=== saitamsaitam/Web-sovelluskehitys_2/Teht_5_XML_dokumentti_ja_nimiavaruuden_maarittava_skeema/Person/employee.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xml>

<person xmlns="http://www.person.fi/employee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.person.fi/employee employeeSchema.xsd">

	<employee>
		<firstname>John</firstname>
		<lastname>Gary</lastname>
		<age>40</age>
		<address>Askistontie</address>
		<city>Vantaa</city>
		<country>Finland</country>
	</employee>

</person>

=== saitamsaitam/Web-sovelluskehitys_2/Teht_3 XML-dokumentti ja DTD/employee.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<person xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./employeeSchema.xsd">

	<employee>
		<firstname>John</firstname>
		<lastname>Gary</lastname>
		<age>40</age>
		<address>Askistontie</address>
		<city>Vantaa</city>
		<country>Finland</country>

	</employee>

</person>
